// This file is auto-generated by Style Class Generator. Do not edit.
// container,config-box,field-row,filler,unity-scroll-view__content-viewport,btn-row

// ReSharper disable All
namespace Tarodev.StyleClassGenerator
{
	public static class StyleClasses
	{
		public const string Container = "container";
		public const string ConfigBox = "config-box";
		public const string FieldRow = "field-row";
		public const string Filler = "filler";
		public const string UnityScrollViewContentViewport = "unity-scroll-view__content-viewport";
		public const string BtnRow = "btn-row";
	}
}
