// This file is auto-generated by Style Class Generator. Do not edit.
// container,config-box,field-row

// ReSharper disable All
namespace Tarodev.AutoSave
{
	public static class Styles
	{
		public const string Container = "container";
		public const string ConfigBox = "config-box";
		public const string FieldRow = "field-row";
	}
}
