// This file is auto-generated by Style Class Generator. Do not edit.
// container,config-container,title-row,error-label,content-container,field-row

// ReSharper disable All
namespace Tarodev.FileWatcher
{
	public static class StyleClasses
	{
		public const string Container = "container";
		public const string ConfigContainer = "config-container";
		public const string TitleRow = "title-row";
		public const string ErrorLabel = "error-label";
		public const string ContentContainer = "content-container";
		public const string FieldRow = "field-row";
	}
}
